spring:
  config:
    activate:
      on-profile: stag

management:
  endpoint:
    health:
      show-details: when_authorized
      enabled: true
    heapdump:
      enabled: false
    shutdown:
      enabled: false

  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health

logging:
  level:
    sql: info
    root: warn
    web: warn

server:
  port: ${SERVER_PORT}