spring:
  profiles:
    group:
      "local": "local, datasource, jwt, redis"
      "stag": "datasource, jwt, redis, log"

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: ${SERVER_PORT:8080}
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
